print("##########################\n")
print("#                        #\n")
print("#    Ikhsan Gymnastiar   #\n")
print("#      2210817310005     #\n")
print("#                        #\n")
print("##########################\n")